### ISSUE TITLE
Named Volumes for Persistence

### ISSUE THREAD

**Issue by safesploit** [safesploit/doogle-docker#2]
## Issue

Currently default volume management in Docker.

## Solution 

Instead, create named volumes for persistent data storage.

This ensures that your database data persists even if containers are recreated or removed. Define named volumes in your docker-compose.yml file

**Comment by safesploit** [comment]
**docker-compose.yml** 

Define named volumes under the volumes section. 
Give each volume a unique name to identify it easily.

```yaml
version: '3.9'
services:
  php-apache-env:
    # ...
  mysql_db:
    # ...
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
```
